/**
 * @module SystemContext
 */

import React, { createContext, useState, useEffect } from "react";
import { System } from "@app/types/system";
import { fetchBlockchainTime } from "@app/services/auctionHouseService";
import { globalSettings } from "@app/config/globalSettings";
import { useTokenClient, useAccessControlsClient } from "@ethereum-tag-service/sdk-react-hooks";
import { useAccount } from "wagmi";

// Define the default values and functions
const defaultSystemContextValue: System = {
  timeDifference: 0,
  blockchainTime: () => Math.floor(Date.now() / 1000),
  updateBlockchainTime: async () => {},
  ownershipTermLength: 0,
  platformAddress: "",
};

export const SystemContext = createContext<System>(defaultSystemContextValue);

type Props = {
  children: React.ReactNode;
};

/**
 * @description Sets up a timer for checking the blockchain time and initializes
 * global system settings by fetching ownership term length and platform address upon
 * mount. It provides the assembled `System` context value to child components through
 * a `Context.Provider`.
 * 
 * @param { React.ReactNode } .children - components that will be passed the system
 * context generated by the component.
 * 
 * @returns { object } a `System` object that contains relevant data for auction house
 * components, including time difference, blockchain time, and ownership term length.
 */
export const SystemProvider: React.FC<Props> = ({ children }: { children: React.ReactNode }) => {
  const [timeDifference, setTimeDifference] = useState(0); // Time difference in seconds
  const [ownershipTermLength, setOwnershipTermLength] = useState(0);
  const [platformAddress, setPlatformAddress] = useState<string>("");
  const { chain, address } = useAccount();
  const { accessControlsClient, getPlatformAddress } = useAccessControlsClient({
    chainId: chain?.id,
    account: address,
  });

  const { tokenClient, getOwnershipTermLength } = useTokenClient({
    chainId: chain?.id,
    account: address,
  });

  const blockchainTime = () => Math.floor(Date.now() / 1000) - timeDifference;

  /**
   * @description Fetches the current blockchain timestamp using the `fetchBlockchainTime`
   * async function, then calculates and updates the time difference between the local
   * time and the blockchain timestamp using the `setTimeDifference` function.
   */
  const updateBlockchainTime = async () => {
    try {
      const blockchainTimestamp = await fetchBlockchainTime();
      const localTime = Math.floor(Date.now() / 1000);
      const difference = localTime - blockchainTimestamp;
      setTimeDifference(difference);
    } catch (error) {
      console.error("Failed to read blockchain time", error);
    }
  };

  /**
   * @description Retrieves and sets global system settings, including ownership term
   * length and platform address.
   */
  const fetchGlobalSettings = async () => {
    try {
      if (tokenClient && accessControlsClient) {
        const termLength = await getOwnershipTermLength();
        setOwnershipTermLength(Number(termLength));
      }
      setPlatformAddress(globalSettings.PLATFORM_ADDRESS);
    } catch (error) {
      console.error("System: Failed to initialize system data:", error);
    }
  };

  useEffect(() => {
    fetchGlobalSettings();
    updateBlockchainTime(); // Initial check on component mount

    const intervalId = setInterval(
      () => {
        updateBlockchainTime(); // Periodic checks
      },
      15 * 60 * 1000, // 15 minutes in milliseconds
    );

    return () => clearInterval(intervalId); // Cleanup on component unmount
  }, [tokenClient, accessControlsClient]);

  // Context value assembled from state and functions.
  const contextValue: System = {
    timeDifference,
    blockchainTime,
    updateBlockchainTime,
    ownershipTermLength,
    platformAddress,
  };

  // Providing the auction house context to child components.
  return <SystemContext.Provider value={contextValue}>{children}</SystemContext.Provider>;
};
