service: defender-as-code-test-project
configValidationMode: error
frameworkVersion: '3'
useDotenv: true
provider:
  name: defender
  stage: ${opt:stage, 'dev'}
  stackName: mystack
  ssot: false
defender:
  key: "${env:TEAM_API_KEY}"
  secret: "${env:TEAM_API_SECRET}"
resources:
  actions:
    release-next-auction-multi:
      name: ReleaseNextAuctionMulti
      trigger:
        type: sentinel
      paused: false
      path: "./dist/defender/actions/release-next-auction-multi"
  policies:
    policy-20:
      eip1559-pricing: true
    policy-SO:
      eip1559-pricing: false
      private-transactions: false
  contracts:
    ets-auction-house-arbitrum-sepolia:
      name: ETSAuctionHouse-ArbitrumSepolia
      address: '0xcbBFB1B7FAf2011c5C3984C8D20759e74C90fdef'
      network: arbitrum-sepolia
    ets-auction-house-base-sepolia:
      name: ETSAuctionHouse-BaseSepolia
      address: '0x945D2C0228dC1Cc872040494Df185629e764b54c'
      network: base-sepolia
  relayers:
    ets-auction-oracle-base-sepolia:
      name: ETSAuctionOracle-BaseSepolia
      network: base-sepolia
      min-balance: '100000000000000000'
      policy: ${self:resources.policies.policy-20}
    ets-auction-oracle:
      name: ETSAuctionOracle-arbitrumSepolia
      network: arbitrum-sepolia
      min-balance: '100000000000000000'
      policy: ${self:resources.policies.policy-SO}
      api-keys:
        - key-1
  notifications:
    discord-actitity-internal:
      type: discord
      name: Discord Actitity (Internal)
      config:
        url: >-
          https://discord.com/api/webhooks/1221279416324460664/4mc9uvUOVpAVyGkd7ZDeOR59ngciOiQFAV9MrwC9S4-76XQ-24EF3eC-cGaYMRddHmv0
      paused: false
  monitors:
    request-create-auction-base-sepolia:
      name: RequestCreateAuction-BaseSepolia
      type: BLOCK
      network: base-sepolia
      addresses:
        - '0x945D2C0228dC1Cc872040494Df185629e764b54c'
      skip-abi-validation: false
      paused: false
      action-trigger: ${self:resources.actions.release-next-auction-multi}
      confirm-level: 1
      notify-config:
        timeout: 0
        message: |-
          **Defender Monitor {{ sentinel.name }} Triggered**

          **Network**

          {{ sentinel.network }}

          **Block Hash**

          {{ blockHash }}

          **Transaction Hash**

          {{ transaction.transactionHash }}

          **Explorer Link**

          {{ transaction.link }}

          **Match Reasons**

          {{ matchReasonsFormatted }}

          **Metadata**

          {{ metadataFormatted }}
        message-subject: 'Defender Monitor: RequestCreateAuctionBaseSepolia triggered'
        channels:
          - ${self:resources.notifications.discord-actitity-internal}
      conditions:
        event:
          - expression: null
            signature: RequestCreateAuction()
    request-create-auction-arbitrum-sepolia:
      name: RequestCreateAuction-ArbitrumSepolia
      type: BLOCK
      network: arbitrum-sepolia
      addresses:
        - '0xcbBFB1B7FAf2011c5C3984C8D20759e74C90fdef'
      skip-abi-validation: false
      paused: false
      action-trigger: ${self:resources.actions.release-next-auction-multi}
      confirm-level: 1
      notify-config:
        timeout: 0
        message: |-
          **Defender Monitor {{ sentinel.name }} Triggered**

          **Network**

          {{ sentinel.network }}

          **Block Hash**

          {{ blockHash }}

          **Transaction Hash**

          {{ transaction.transactionHash }}

          **Explorer Link**

          {{ transaction.link }}

          {{ matchReasonsFormatted }}
        message-subject: 'Defender Monitor: RequestCreateAuction triggered'
        channels:
          - ${self:resources.notifications.discord-actitity-internal}
      conditions:
        event:
          - expression: null
            signature: RequestCreateAuction()
  forked-networks: {}
  private-networks: {}
  block-explorer-api-keys: {}
plugins:
  - '@openzeppelin/defender-as-code'
