import { useState } from "react";
import type { NextPage } from "next";
import useTranslation from "next-translate/useTranslation";
import Layout from "@app/layouts/default";
import { useRelayers } from "@app/hooks/useRelayers";
import { useAccount } from "wagmi";
import { availableChainIds } from "@app/config/wagmiConfig";
import { isValidTag } from "@app/utils/tagUtils";
import useToast from "@app/hooks/useToast";
import TagInput from "@app/components/TagInput";
import { TagInput as TagInputType } from "@app/types/tag";
import { useTokenClient, useRelayerClient } from "@ethereum-tag-service/sdk-react-hooks";

/**
 * @description Provides documentation for code that is given to it. It generates
 * high-quality documentation using the information provided to it, including the
 * creation and management of tags, relayers, and a tag input field.
 * 
 * @returns { array } a React component that displays a form for creating and managing
 * tags, including a select box for choosing a relayers and a button to create new tags.
 */
const Playground: NextPage = () => {
  const { t } = useTranslation("common");
  const { showToast, ToastComponent } = useToast();
  const { chain, isConnected, address } = useAccount();
  const [tags, setTags] = useState<TagInputType[]>([]);
  const [selectedRelayer, setSelectedRelayer] = useState<any | null>(null);
  const { tagExists } = useTokenClient({
    chainId: chain?.id,
    account: address,
  });

  const { createTags } = useRelayerClient({
    relayerAddress: selectedRelayer?.id,
    account: address,
    chainId: chain?.id,
  });
  const [isCreatingTag, setIsCreatingTag] = useState(false);
  const { relayers } = useRelayers({});
  const isCorrectNetwork = chain?.id && availableChainIds.includes(chain?.id as any);
  const disabled = !tags.length || !selectedRelayer || !isCorrectNetwork || isCreatingTag;

  /**
   * @description Verifies input conditions and returns a tooltip message accordingly:
   * disconnects wallet, ensures tag length or selects a relay network.
   * 
   * @returns { string } a string of text depending on the input provided.
   */
  const getTooltipMessage = () => {
    if (!isConnected) return t("connect-wallet");
    if (!tags.length) return t("please-enter-a-tag");
    if (!selectedRelayer) return t("please-select-a-relayer");
    //if (!isCorrectNetwork) return t("connect");
    if (isCreatingTag) return t("creating-tags");
    return "";
  };

  /**
   * @description Sets the `SelectedRelayer` state to the selected relayers from an event.
   * 
   * @param { React.ChangeEvent<HTMLSelectElement> } event - Select event generated by
   * the user selecting an option from the select element, providing the value of the
   * selected option to the function.
   */
  const handleSelectRelayer = (event: React.ChangeEvent<HTMLSelectElement>) => {
    const relayerId = event.target.value;
    const selected = relayers.find((relayer: any) => relayer.id.toString() === relayerId);
    setSelectedRelayer(selected || null);
  };

  /**
   * @description Sets the `isCreatingTag` state to `true` and tries to create tags
   * using the `createTags` method. If successful, it sets the `tags` state to an empty
   * array and shows a toast message with the newly created tags. If failed, it shows
   * an error toast message. Finally, it sets `isCreatingTag` to `false`.
   */
  const handleCreateTags = async () => {
    if (!disabled) {
      setIsCreatingTag(true);
      try {
        if (tags.length > 0) {
          const tagValues = tags.map((tag) => tag.text);
          await createTags?.(tagValues);
        }

        setTags([]);

        const successMessage = (
          <>
            {t("tag-created-successfully")}{" "}
            {tags.map((tag, index) => (
              <span key={index}>
                <a
                  href={`/tags/${tag.text.startsWith("#") ? tag.text.slice(1) : tag.text}`}
                  className="link link-primary"
                  style={{ textDecoration: "underline" }}
                >
                  {tag.text}
                </a>
                {index !== tags.length - 1 && ", "}
              </span>
            ))}
            .
          </>
        );
        showToast({
          title: "Success",
          description: successMessage,
        });
      } catch (error) {
        showToast({
          title: "Error",
          description: t("failed-to-create-tags"),
        });
      } finally {
        setIsCreatingTag(false);
      }
    }
  };

  /**
   * @description Filters tags and removes a specific tag from the filtered array of tags.
   * 
   * @param { number } i - index of the tag to be removed from the array of tags passed
   * to the `setTags` function.
   */
  const handleDeleteTag = (i: number) => {
    setTags(tags.filter((tag, index) => index !== i));
  };

  /**
   * @description Checks if a new tag is valid and if it already exists, then adds it
   * to the list or shows an error message.
   * 
   * @param { TagInputType } tag - tag that needs to be checked for its existence in
   * the system.
   */
  const handleAddTag = async (tag: TagInputType) => {
    if (isValidTag(tag.text)) {
      const exists = await tagExists?.(tag.text);
      if (exists) {
        showToast({
          description: t("tag-already-exists"),
        });
      } else {
        setTags((prevTags) => [...prevTags, tag]);
      }
    } else {
      showToast({
        description: t("invalid-tag-message"),
      });
    }
  };

  return (
    <Layout>
      <div className="space-y-4" style={{ width: "300px" }}>
        <TagInput tags={tags} handleDeleteTag={handleDeleteTag} handleAddTag={handleAddTag} />
        <div className="relative">
          {/**
           * @description Is used to display a list of relays and allow users to choose one to
           * use for a transaction.
           * 
           * @param { string } className - class name to assign to the select element.
           * 
           * @param { string } value - current selected relayer's ID, which is updated when the
           * user selects a new option from the select menu.
           * 
           * @param { event handler. } onChange - handler that is called when the selected
           * relayer changes, providing the new value of the selected relayer through the `value`
           * property.
           * 
           * 	* `handleSelectRelayer`: This is the function that will be called when the user
           * selects a new relayer from the dropdown menu. It receives the `event` object as
           * an argument, which contains information about the user's selection, such as the
           * `target.value` property.
           * 	* `selectedRelayer`: This is a property that stores the previously selected relayer
           * ID, or an empty string if no relayer has been selected yet. This property is passed
           * as a prop to the function, so it can be accessed and used within the function.
           */}
          <select
            className="select select-bordered w-full max-w-xs"
            value={selectedRelayer ? selectedRelayer?.id : ""}
            onChange={handleSelectRelayer}
          >
            <option disabled value="">
              {t("select-a-relayer")}
            </option>
            {relayers?.map((relayer: any, index: number) => (
              <option key={index} value={relayer.id}>
                {relayer.name}
              </option>
            ))}
          </select>
        </div>
        <div className={`${disabled ? "tooltip" : ""}`} data-tip={getTooltipMessage()}>
          <button
            onClick={handleCreateTags}
            disabled={disabled}
            className={`btn ${disabled ? "btn-disabled" : "btn-primary"}`}
          >
            {isCreatingTag ? "Creating..." : t("create")}
          </button>
        </div>
      </div>
      {ToastComponent}
    </Layout>
  );
};

export default Playground;
