name: ✨ Feature Request
description: Got a cool idea? We'd love to hear it!
title: "[Feature]: "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Awesome! Feature requests are the best kind of issues. 🚀
        
        Don't overthink it - just tell us what would make your life better!

  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: Help us understand the pain point
      placeholder: "Every time I want to do X, I have to do Y and Z first, and it's annoying because..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: What would you like to see?
      description: Describe your ideal solution
      placeholder: "It would be amazing if I could just click a button and..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Any other ideas?
      description: Alternative approaches or workarounds you've considered
      placeholder: "I thought about doing X, but that would be weird because..."

  - type: textarea
    id: context
    attributes:
      label: Anything else?
      description: Screenshots, mockups, links to similar features elsewhere
      placeholder: "Here's a crude drawing I made on a napkin..."