name: Changesets
on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    name: Verify
    uses: ./.github/workflows/verify.yml
    secrets: inherit

  changesets:
    name: Publish
    #needs: verify
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 8

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Install dependencies
        uses: ethereum-tag-service/actions/.github/actions/pnpm@main

      - name: Verify npm authentication  # This will run third
        run: |
          npm config set "//registry.npmjs.org/:_authToken" "${NPM_TOKEN}"
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Version and Publish
        id: publish
        run: |
          pnpm changeset version
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "chore: version packages" || echo "No changes to commit"
          pnpm changeset:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NETWORK: arbitrumSepolia

      - name: Push changes
        run: |
          git push --follow-tags
