name: Changesets

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref to run workflow on (branch, tag, or commit SHA)'
        required: true
        default: 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  #verify:
  #  name: Verify
  #  uses: ./.github/workflows/verify.yml
  #  secrets: inherit

  changesets:
    name: Create version pull request
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.ref || github.ref }}

      - name: Install dependencies
        uses: ethereum-tag-service/actions/.github/actions/pnpm@main

      - name: Create Version Pull Request
        uses: changesets/action@v1.4.9
        with:
          commit: 'chore: version packages'
          title: 'chore: version packages'
          version: pnpm changeset:version
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.ref || github.ref }}

      - name: Install dependencies
        uses: ethereum-tag-service/actions/.github/actions/pnpm@main

      - name: Publish
        uses: changesets/action@v1.4.9
        with:
          publish: pnpm changeset:publish
          createGithubReleases: ${{ github.ref == 'refs/heads/main' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NETWORK: arbitrumSepolia

