name: Set Default Value for Issue Status

on:
  issues:
    types: [opened]

jobs:
  set-default-value:
    runs-on: ubuntu-latest
    steps:
      - name: Set default value for custom Status field
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }} \
            -d '{"custom_fields": {"PVTSSF_lADOBbsxY84AAXYjzgAMa04": "5b62998f"}}'
