# Primary orchestrator workflow for pull request validation and testing
#
# Key responsibilities:
# 1. Validates branch rules:
#    - Changes to apps/* must target stage branch
#    - Changes to packages/* must target main branch
# 2. Sets up the development environment:
#    - Installs Node.js and PNPM
#    - Caches the workspace for downstream workflows
# 3. Triggers verify.yml for code quality checks
# 4. Analyzes size impact for package changes targeting main
#
# The workspace cache (keyed by github.sha) is consumed by:
# - verify.yml
# - solidity-screener.yml
name: Pull Request
on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  validate-branch-rules:
    name: Validate Branch Rules
    runs-on: ubuntu-latest
    steps:
      - name: Check target branch
        if: github.base_ref != 'stage' && !(github.base_ref == 'main' && github.head_ref == 'stage')
        run: |
          echo "Error: All pull requests must target the 'stage' branch"
          echo "Current target branch: ${{ github.base_ref }}"
          echo "Please update your PR to target the stage branch"
          exit 1

  setup:
    name: Setup
    needs: validate-branch-rules
    runs-on: ubuntu-latest
    outputs:
      pnpm_home: ${{ steps.pnpm-path.outputs.path }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 10.14.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.1.0
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Cache workspace
        uses: actions/cache@v3
        with:
          path: ./*
          key: ${{ github.sha }}


  verify:
    name: Verify
    needs: setup
    uses: ./.github/workflows/verify.yml
    secrets: inherit

  size:
    name: Size
    needs: setup
    if: |
      github.base_ref == 'main' &&
      contains(toJSON(github.event.pull_request.files.*.path), 'packages/')
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Restore workspace
        uses: actions/cache@v3
        with:
          path: ./*
          key: ${{ github.sha }}

      - name: Report build size
        uses: preactjs/compressed-size-action@v2
        with:
          pattern: "packages/**/dist/**"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          NETWORK: arbitrumSepolia
