name: Pull Request
on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  verify:
    name: Verify
    uses: ./.github/workflows/verify.yml
    secrets: inherit

  size:
    name: Size
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: read # Read access to clone the repository and read contents
      pull-requests: write # Write access to post comments on the pull request

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ethereum-tag-service/actions/.github/actions/pnpm@main

      - name: Report build size
        uses: preactjs/compressed-size-action@v2
        with:
          pattern: "packages/**/dist/**"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          NETWORK: testnet_stage
