name: Pull Request
on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  validate-branch-rules:
    name: Validate Branch Rules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check branch rules
        id: check-changes
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})

          echo "Changed files:"
          echo "$CHANGED_FILES"

          HAS_APP_CHANGES=$(echo "$CHANGED_FILES" | grep '^apps/' || true)
          HAS_PACKAGE_CHANGES=$(echo "$CHANGED_FILES" | grep '^packages/' || true)

          echo "App changes: '$HAS_APP_CHANGES'"
          echo "Package changes: '$HAS_PACKAGE_CHANGES'"

          if [[ -n "$HAS_APP_CHANGES" ]] && [[ "${{ github.base_ref }}" != "stage" ]]; then
            echo "Error: Changes detected in /apps/* directory"
            echo "Current target branch: ${{ github.base_ref }}"
            echo "Required target branch: stage"
            echo "Please update your PR to target the stage branch for all changes to /apps/*"
            exit 1
          fi

          if [[ -n "$HAS_PACKAGE_CHANGES" ]] && [[ "${{ github.base_ref }}" != "main" ]]; then
            echo "Error: Changes detected in /packages/* directory"
            echo "Current target branch: ${{ github.base_ref }}"
            echo "Required target branch: main"
            echo "Please update your PR to target the main branch for all changes to /packages/*"
            exit 1
          fi


  verify:
    name: Verify
    needs: validate-branch-rules
    uses: ./.github/workflows/verify.yml
    secrets: inherit

  size:
    name: Size
    needs: validate-branch-rules
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: |
      github.base_ref == 'main' &&
      contains(toJSON(github.event.pull_request.files.*.path), 'packages/')

    permissions:
      contents: read # Read access to clone the repository and read contents
      pull-requests: write # Write access to post comments on the pull request

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ethereum-tag-service/actions/.github/actions/pnpm@main

      - name: Report build size
        uses: preactjs/compressed-size-action@v2
        with:
          pattern: "packages/**/dist/**"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          NETWORK: ${{ github.base_ref == 'main' && 'testnet_stage' || 'arbitrumSepolia' }}

