name: Solidity screener

env:
  MNEMONIC_LOCAL: test test test test test test test test test test test junk
  ETHERNAL_DISABLED: true

on:
  workflow_call:
    inputs:
      cache-key:
        required: true
        type: string

jobs:
  changes:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      contracts: ${{ steps.filter.outputs.contracts }}
      tests: ${{ steps.filter.outputs.tests }}
    steps:
      - name: Restore workspace
        uses: actions/cache@v3
        with:
          path: ./*
          key: ${{ inputs.cache-key }}

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            contracts:
              - 'packages/contracts/contracts/**'
            tests:
              - 'packages/contracts/**'

  lint:
    name: Solhint
    needs: changes
    if: ${{ needs.changes.outputs.contracts == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Restore workspace
        uses: actions/cache@v3
        with:
          path: ./*
          key: ${{ inputs.cache-key }}

      - name: Set PNPM path
        run: echo "PATH=/home/runner/setup-pnpm/node_modules/.bin:$PATH" >> $GITHUB_ENV

      - name: Run Solhint
        run: |
          cd packages/contracts/
          pnpm run solhint

  test:
    name: Contract Tests
    needs: changes
    if: ${{ needs.changes.outputs.tests == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Restore workspace
        uses: actions/cache@v3
        with:
          path: ./*
          key: ${{ inputs.cache-key }}

      - name: Set PNPM path
        run: echo "PATH=/home/runner/setup-pnpm/node_modules/.bin:$PATH" >> $GITHUB_ENV

      - name: Run Tests
        run: |
          cd packages/contracts
          pnpm run test
