name: Sync Stage

on:
  workflow_run:
    workflows: ["Changesets"]
    types:
      - completed
    branches:
      - main

jobs:
  sync:
    name: Sync main to stage
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Sync main to stage
        run: |
          git fetch origin stage:stage
          git checkout stage
          git merge origin/main
          git push origin stage
