name: Sync Stage

on:
  push:
    branches:
      - main

jobs:
  sync:
    name: Sync main to stage
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: stage

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Sync main to stage
        run: |
          git fetch origin main
          git merge origin/main
          git push origin stage
