name: Verify

on:
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
      - name: Restore workspace
        uses: actions/cache@v3
        with:
          path: ./*
          key: ${{ github.sha }}

      - name: Set PNPM path
        run: echo "PATH=${{ needs.setup.outputs.pnpm_home }}/bin:$PATH" >> $GITHUB_ENV

      - name: Lint repo
        run: pnpm lint:repo

      - name: Lint code
        run: pnpm lint

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Restore workspace
        uses: actions/cache@v3
        with:
          path: ./*
          key: ${{ github.sha }}

      - name: Set PNPM path
        run: echo "PATH=${{ needs.setup.outputs.pnpm_home }}/bin:$PATH" >> $GITHUB_ENV

      - name: Build
        run: pnpm build
        env:
          NETWORK: arbitrumSepolia

      - name: Publint
        run: pnpm test:build

      - name: Check for unused files, dependencies, and exports
        run: pnpm knip --production

  test:
    name: Smart Contracts
    uses: ./.github/workflows/solidity-screener.yml
    with:
      cache-key: ${{ github.sha }}
    secrets: inherit
