name: Verify
on:
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 8

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ethereum-tag-service/actions/.github/actions/pnpm@main

      - name: Lint repo
        run: pnpm lint:repo

      - name: Lint code
        run: pnpm lint

      - name: Update package versions
        run: pnpm version:update

      # Debug: Print current GitHub context
      - name: Debug - Print GitHub context
        run: echo '${{ toJson(github) }}'

      # Debug: Print current git status
      - name: Debug - Git status before auto-commit
        run: git status

      # Auto-commit changes
      - name: Auto-commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        env:
          # Provide the action with a GitHub token for authentication
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Specify the commit message for the automated commit
          commit_message: 'chore: format'
          commit_user_name: 'github-actions[bot]'
          commit_user_email: 'github-actions[bot]@users.noreply.github.com'
          # Dynamically set the branch name:
          # - For pull requests, use the head branch name (github.head_ref)
          # - For direct pushes, use the current branch name (github.ref_name)
          branch: ${{ github.head_ref || github.ref_name }}
          # Skip pre-commit hooks to avoid potential issues with automated commits
          commit_options: '--no-verify'
          # Skip fetching the latest changes from the remote to improve performance
          skip_fetch: true

      # Debug: Print git status after auto-commit
      - name: Debug - Git status after auto-commit
        run: git status

      # Debug: Print last commit
      - name: Debug - Show last commit
        run: git log -1

  build:
    name: Build
    needs: lint
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ethereum-tag-service/actions/.github/actions/pnpm@main

      - name: Build
        run: pnpm build

      - name: Publint
        run: pnpm test:build

      - name: Check for unused files, dependencies, and exports
        run: pnpm knip --production
